//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxViewClock.i18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Months {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Months() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxViewClock.i18n.Months", typeof(Months).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendemmiaio.
        /// </summary>
        internal static string m01 {
            get {
                return ResourceManager.GetString("m01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brumaio.
        /// </summary>
        internal static string m02 {
            get {
                return ResourceManager.GetString("m02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frimaio.
        /// </summary>
        internal static string m03 {
            get {
                return ResourceManager.GetString("m03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevoso.
        /// </summary>
        internal static string m04 {
            get {
                return ResourceManager.GetString("m04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piovoso.
        /// </summary>
        internal static string m05 {
            get {
                return ResourceManager.GetString("m05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventoso.
        /// </summary>
        internal static string m06 {
            get {
                return ResourceManager.GetString("m06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germinale.
        /// </summary>
        internal static string m07 {
            get {
                return ResourceManager.GetString("m07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiorile.
        /// </summary>
        internal static string m08 {
            get {
                return ResourceManager.GetString("m08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pratile.
        /// </summary>
        internal static string m09 {
            get {
                return ResourceManager.GetString("m09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messidoro.
        /// </summary>
        internal static string m10 {
            get {
                return ResourceManager.GetString("m10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termidoro.
        /// </summary>
        internal static string m11 {
            get {
                return ResourceManager.GetString("m11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruttidoro.
        /// </summary>
        internal static string m12 {
            get {
                return ResourceManager.GetString("m12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanculottidi.
        /// </summary>
        internal static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
    }
}
