//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxViewClock.i18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MonthsDes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonthsDes() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxViewClock.i18n.MonthsDes", typeof(MonthsDes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alla vendemmia che avviene da settembre a ottobre.
        /// </summary>
        internal static string m01 {
            get {
                return ResourceManager.GetString("m01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alle nebbie e brume basse che sono la trasudazione della natura da ottobre a novembre.
        /// </summary>
        internal static string m02 {
            get {
                return ResourceManager.GetString("m02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a al freddo, a volte asciutto, a volte umido, che si fa sentire da novembre a dicembre.
        /// </summary>
        internal static string m03 {
            get {
                return ResourceManager.GetString("m03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alla neve che imbianca la terra da dicembre a gennaio.
        /// </summary>
        internal static string m04 {
            get {
                return ResourceManager.GetString("m04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alle piogge che cadono in genere più copiosamente da gennaio a febbraio.
        /// </summary>
        internal static string m05 {
            get {
                return ResourceManager.GetString("m05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a agli acquazzoni che hanno luogo, e ai venti che seccano la terra da febbraio a marzo.
        /// </summary>
        internal static string m06 {
            get {
                return ResourceManager.GetString("m06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alla fermentazione e allo sviluppo della linfa da marzo ad aprile.
        /// </summary>
        internal static string m07 {
            get {
                return ResourceManager.GetString("m07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alla sbocciatura dei fiori da aprile a maggio.
        /// </summary>
        internal static string m08 {
            get {
                return ResourceManager.GetString("m08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a alla fecondità ridente dei prati e alla raccolta delle messi da maggio a giugno.
        /// </summary>
        internal static string m09 {
            get {
                return ResourceManager.GetString("m09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a all&apos;aspetto delle spighe ondeggianti e delle mietiture dorate che coprono i campi da giugno a luglio.
        /// </summary>
        internal static string m10 {
            get {
                return ResourceManager.GetString("m10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a al calore allo stesso tempo solare e terrestre che infiamma l&apos;aria da luglio ad agosto.
        /// </summary>
        internal static string m11 {
            get {
                return ResourceManager.GetString("m11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ai frutti che il sole dora e fa maturare da agosto a settembre.
        /// </summary>
        internal static string m12 {
            get {
                return ResourceManager.GetString("m12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ai pochi giorni per allineare le decadi alla rivoluzione terrestre.
        /// </summary>
        internal static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
    }
}
